parameters:
  artifactName: 'Unknow'
  platform: 'Linux'
  versionSuffix: 'unknow'
steps:
  - script: dotnet restore src
    displayName: Restore packages
  - bash: |
      mkdir artifacts
      dotnet pack src -c Release -o "$(Build.SourcesDirectory)/artifacts" --version-suffix "ci.$VERSIONSUFFIX.$(Build.BuildNumber)"
    env:
      VERSIONSUFFIX: ${{ parameters.versionSuffix }}
    displayName: Build
  - script: dotnet test src/Netatmo.Tests/Netatmo.Tests.csproj -c Release -l trx
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Tests
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      platform: ${{ parameters.platform }}
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathToPublish: artifacts
      artifactName: ${{ parameters.artifactName }}
